---
- name: Create consul cluster
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
  - name: Create /opt/consul
    file:
      state: directory
      path: "{{ item }}"
      owner: "{{ app_owner }}"
      mode: "0775"
    become: true
    with_items:
      - /opt/consul
      - /opt/consul/config

  - name: Unzip consul
    unarchive:
        src: "artifact/consul.zip"
        dest: "/opt/consul"
        mode: 0775

  - name: Copy consul systemd configuration to app server
    copy:
        src: "files/consul.service"
        dest: /etc/systemd/system/consul.service
    become: true

  - name: Start consul service
    service:
      name: consul
      state: started
    become: true
